import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  OnInit,
  signal,
} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { firstValueFrom } from 'rxjs';

import { OtpInputComponent } from '../../components/common/otp-input/otp-input.component';
import { AuthService } from '../../services/auth.service';
import { AuthSessionService } from '../../services/auth-session.service';
import { ReactiveFormsModule, FormGroup, FormControl } from '@angular/forms';

@Component({
  selector: 'app-two-factor-page',
  imports: [OtpInputComponent, ReactiveFormsModule],
  templateUrl: './two-factor-page.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: 'flex flex-col items-center gap-8 w-full max-w-[440px]',
  },
})
export class TwoFactorPageComponent implements OnInit {
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  private readonly authService = inject(AuthService);
  private readonly authSession = inject(AuthSessionService);

  protected formGroup!: FormGroup;

  protected readonly submitted = signal(false);
  protected readonly isProcessing = signal(false);
  protected readonly fullCode = signal('');
  protected readonly errorMessage = signal<string | null>(null);

  private readonly userId = this.route.snapshot.queryParamMap.get('user_id') ?? '';
  private readonly method = this.route.snapshot.queryParamMap.get('method') ?? 'authenticator';
  private readonly maskedPhone = this.route.snapshot.queryParamMap.get('masked_phone') ?? '';
  private readonly email = this.route.snapshot.queryParamMap.get('email') ?? '';

  protected readonly isCodeComplete = computed(() => this.fullCode().length === 6);
  protected readonly description = computed(() => {
    if (this.method === 'email') {
      return this.email
        ? `To continue, kindly enter the 6 digit code we sent to ${this.email}`
        : 'To continue, kindly enter the 6 digit code we sent to your email';
    }

    if (this.method === 'sms') {
      return this.maskedPhone
        ? `To continue, kindly enter the 6 digit code we sent to ${this.maskedPhone}`
        : 'To continue, kindly enter the 6 digit code we sent to your phone';
    }

    return 'To continue, kindly enter your 6 digit code generated by your authenticator app';
  });

  protected onCodeChange(code: string): void {
    this.fullCode.set(code);
    this.errorMessage.set(null);
  }

  protected async onSubmit(): Promise<void> {
    this.submitted.set(true);

    if (!this.isCodeComplete() || !this.userId) {
      return;
    }

    this.isProcessing.set(true);
    this.errorMessage.set(null);

    try {
      const response = await firstValueFrom(
        this.authService.verifyTwoFactorLogin({
          user_id: this.userId,
          code: this.fullCode(),
        }),
      );

      this.authSession.saveLoginSession(response, null);
      const isSessionStable = await this.stabilizeAuthenticatedSession();

      if (!isSessionStable) {
        this.authSession.clearSession();
        this.errorMessage.set(
          'We verified your code, but could not finish signing you in. Please try again.',
        );
        return;
      }

      await this.router.navigate(this.resolvePostLoginRoute(response.user?.role));
    } catch (error: unknown) {
      this.errorMessage.set(
        this.readBackendMessage(error) ?? 'We couldn’t verify that code right now. Please try again.',
      );
    } finally {
      this.isProcessing.set(false);
    }
  }

  private resolvePostLoginRoute(role: string | undefined): string[] {
    return role === 'admin' ? ['/admin'] : ['/en'];
  }

  private async stabilizeAuthenticatedSession(): Promise<boolean> {
    for (let attempt = 0; attempt < 8; attempt += 1) {
      try {
        const profile = await firstValueFrom(this.authService.getProfile());
        this.authSession.initializeFromProfile(profile);
        return true;
      } catch {
        await this.delay(250 * (attempt + 1));
      }
    }

    return false;
  }

  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => {
      setTimeout(resolve, ms);
    });
  }

  private readBackendMessage(error: unknown): string | null {
    if (!error || typeof error !== 'object') {
      return null;
    }

    const record = error as Record<string, unknown>;
    const payload =
      typeof record['error'] === 'object' && record['error'] !== null
        ? (record['error'] as Record<string, unknown>)
        : null;

    const candidates = [
      payload?.['detail'],
      payload?.['message'],
      payload?.['code'],
      payload?.['non_field_errors'],
    ];

    for (const candidate of candidates) {
      if (typeof candidate === 'string' && candidate.trim().length > 0) {
        return candidate;
      }

      if (Array.isArray(candidate) && candidate.length > 0 && typeof candidate[0] === 'string') {
        return candidate[0];
      }
    }

    return null;
  }
  ngOnInit(): void {
    this.formGroup = new FormGroup({
      otp: new FormControl(''),
    });
    if (!this.userId) {
      this.router.navigate(['/sign-in']);
    }
  }
}
